default-environment: dev

production-environment: dev # As we have only one env. Add more envs if required

defaults:
  working_directory: ./terraform/modules
  var-files:
    paths:
      - ./terraform/config/terraform_config.tfvars

environments:
  dev:
    working_directory: ./terraform/modules
    var-files:
      paths:
        - ./terraform/config/terraform_config.tfvars
