default-environment: dev

production-environment:
  - dev

environments:
  dev:
    working-directory: ./terraform/modules
    var-files:
      paths:
        - ./terraform/config/terraform_config.tfvars
