default-environment: dev

production-environments:
  - prod

environments:
  dev:
    working_directory: ./terraform/modules
    var-files:
      paths:
        - ./terraform/config/terraform_config.tfvars
