default-environment: dev

production-environments:
  - dev

environments:
  dev:
    working-directory: ./terraform/modules
    backend-configs:
      paths:
        - ./terraform/config/terraform_backend.conf
    var-files:
      paths:
        - ./terraform/config/terraform_config.tfvars
      
