name: "Run python unit tests"

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  unit-tests:
    name: Python Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Setup virtual environment and install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install --upgrade pip
          pip install -r src/layers/packages/requirements.

      - name: Run unit tests
        run: |
          . venv/bin/activate
          PYTHONPATH=. pytest
